version: '3.9'

services:
  mysqldb:
    image: mysql:8.0.30
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql_db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 6

  cotacao-crypto:
    depends_on:
      mysqldb:
        condition: service_healthy
    image: alexdamiao86/cotacao-crypto-api:1.1.0
    container_name: cotacao-crypto
    ports:
      - "5555:5555"
    environment:
      - MYSQLDB_HOST=$MYSQLDB_HOST
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQLDB_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQLDB_DATABASE=$MYSQLDB_DATABASE
      - MYSQLDB_DOCKER_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    healthcheck:
      test: "curl --fail -s http://localhost:5555/health/ || exit 1"
      start_period: 30s
      interval: 10s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:15.1
    container_name: postgres
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 3s
      retries: 3

  pgadmin:
    depends_on:
      postgres:
        condition: service_healthy
    image: dpage/pgadmin4:6.16
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin@email.com'
      PGADMIN_DEFAULT_PASSWORD: 'senha'
    ports:
      - "16543:80"

  carteira-crypto:
    depends_on:
      postgres:
        condition: service_healthy
      cotacao-crypto:
        condition: service_healthy
    image: alexdamiao86/carteira-crypto-api:1.0.6
    container_name: carteira-crypto
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_DOCKER_PORT=$POSTGRES_DOCKER_PORT
      - COTACAO_API_URL=$COTACAO_API_URL
    ports:
      - "8080:8080"

volumes:
  postgres_db:
  mysql_db:
